name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: جلب الكود
        uses: actions/checkout@v4

      - name: تجهيز الجافا
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: إعطاء صلاحية التشغيل
        run: chmod +x gradlew

      - name: طبخ الـ APK
        run: ./gradlew assembleDebug

      - name: رفع ملف التطبيق الجاهز
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/*.apk
